spring.application.name=JobHub

github.token=${GITHUB_TOKEN}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_ADDRESS}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=${JWT_SECRET}
jwt.access-token-expiry-ms=900000
jwt.refresh-token-expiry-ms=604800000

app.default-image-url=https://api.dicebear.com/9.x/notionists/svg?seed=%24%7BprofileUsername%7D&backgroundColor=e2e8f0

sandbox.images[0].image-name=coderunner-java
sandbox.images[0].dockerfile-dir=docker/coderunner-java