spring.application.name=JobHub

github.token=${GITHUB_TOKEN:}
stackoverflow.key=${STACKOVERFLOW_KEY:}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jobhub}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_ADDRESS:noreply@jobhub.com}
spring.mail.password=${MAIL_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLXRlc3RpbmctcHVycG9zZXMtb25seS0xMjM0NTY=}
jwt.access-token-expiry-ms=604800000
jwt.refresh-token-expiry-ms=604800000

app.default-image-url=https://api.dicebear.com/9.x/notionists/svg?seed=%24%7BprofileUsername%7D&backgroundColor=e2e8f0

services.embedding-api.base-url=${EMBEDDING_API_URL:http://localhost:8001}

sandbox.image-java=coderunner-java
sandbox.runtime-user=10001:10001
sandbox.images[0].image-name=${sandbox.image-java}
sandbox.images[0].dockerfile-dir=docker/coderunner-java
sandbox.image-python=coderunner-python
sandbox.images[1].image-name=${sandbox.image-python}
sandbox.images[1].dockerfile-dir=docker/coderunner-python
